# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Soporte-Slender-130
Description of the Site: usamos esta pagina para que las personas visiten a nuestro sitio oficial para que consulte nuestro publicidad
description:  Somos de la empresa de Soporte y Mantenimiento, LLevamos casi 3 años, NUESTROS TECNICOS VIENEN DE LAS MEJORES ESCUELAS DE TODO EL MUNDO
Tambien ofrecemos mantenimiento preventivo y Correctivo para brindarle un buen servicio 
Nosotros usamos herramienta para reparar dispositivos electronicos como por ejemplo laptops celulares cuando tienen fallas. Es por eso que estamos aqui para ayudarte a resolver a solucionarlo 
también brindamos apoyo técnico vía remota. 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact:Tambien No te olvides contactarnos realizando las siguientes fuentes mediante redes sociales facebook twiter etc. Para que usted nos conosca quienes y porque ayudamos a las personas a darle soporte y mantenimiento
mantenimiento
# If you don't want to use any icon, you can leave them blank.
email: cesar117bc@gmail.com
facebook_username: VENDETA130   
twitter_username: 
instagram_username: 
linkedin_username: 
github_username: CesarUscanga694
youtube_channel_id: 1234219RRRRRRR
reddit_username: /
behance_username: /
dribbble_username: 
spotify_username:/ UltimateSpiderman69

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
